spring:
  application:
    name: qiyu-live-user-provider
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:qiyu-db-sharding.yaml
    hikari:
      pool-name: qiyu-user-pool
      minimum-idle: 15
      maximum-pool-size: 300
#      connection-init-sql: select 1
      connection-timeout: 4000
      max-lifetime: 60000
      idle-timeout: 60000
  data:
    redis:
      host: 123.60.49.130
      port: 6379
      password: redis_1120
      lettuce:
        pool:
          min-idle: 10   #最小空闲连接
          max-active: 50  #最大连接
          max-idle: 20   #最大空闲连接

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://123.60.49.130:8848?namespace=qiyu-live-test
  protocol:
    name: dubbo
    port: 9091

qiyu:
  rmq:
    producer:
      namesrvAddr: 123.60.49.130:9876
      producerGroup: ${spring.application.name}
      retryTimes: 3
      sendTimeOut: 3000
    consumer:
      namesrvAddr: 123.60.49.130:9876
      consumerGroup: ${spring.application.name}